# Usando uma imagem base do Python
FROM python:3.10-slim

# Definindo o diretório de trabalho dentro do container
WORKDIR /C216-L1_Aula3

# Copiando o arquivo Python para o diretório de trabalho no container
COPY sistema_faculdade.py .

# Comando para executar o script Python
CMD ["python", "sistema_faculdade.py"]
